require: rubocop-rspec
Style/Documentation:
  Enabled: false
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'bin/*'
    - 'lib/tasks/*'
    - 'script/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/migrations/*'
    - 'db/schema.rb'
