require: rubocop-rspec
Style/Documentation:
  Enabled: false
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'bin/*'
    - 'lib/tasks/*'
    - 'script/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'spec/rails_helper.rb'

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Max: 40

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/ScatteredSetup:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false
