---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/reservations/online":
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/reservations/offline":
    post:
      summary: create_offline reservation
      responses:
        '200':
          description: successful
  "/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
  "/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    patch:
      summary: update reservation
      responses:
        '200':
          description: successful
    put:
      summary: update reservation
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
